CREATE TABLE IF NOT EXISTS logistics.causales_devolucion (
  id SERIAL PRIMARY KEY,
  codigo VARCHAR(20),
  nombre VARCHAR(200) NOT NULL,
  concepto VARCHAR(100) DEFAULT 'Devolución de venta',
  notas VARCHAR(200),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_causales_devolucion_nombre UNIQUE (nombre)
);

CREATE INDEX IF NOT EXISTS idx_causales_devolucion_activo
  ON logistics.causales_devolucion(activo);

INSERT INTO logistics.causales_devolucion (codigo, nombre, concepto, notas, activo) VALUES
  ('01', 'VENCIDO O PROXIMO A VENCER', 'Devolución de venta', 'CALIDAD', TRUE),
  ('02', 'CHOQUE TERMICO', 'Devolución de venta', 'CALIDAD', TRUE),
  ('03', 'PERDIDA DE VACIO', 'Devolución de venta', 'CALIDAD', TRUE),
  ('04', 'PROBLEMAS EN EL EMPAQUE', 'Devolución de venta', 'CALIDAD', TRUE),
  ('05', 'SENSORIALES(COLOR,SABOR,OLOR,OBJETOSEXT)', 'Devolución de venta', 'CALIDAD', TRUE),
  ('06', 'ORDEN VENCIDA', 'Devolución de venta', 'COMERCIAL/LOGISTICA', TRUE),
  ('07', 'NO RECIBIDO POR SOBRE STOCK', 'Devolución de venta', 'COMERCIAL', TRUE),
  ('08', 'PUNTO DE VENTA EN INVENTARIO', 'Devolución de venta', 'COMERCIAL/LOGISTICA', TRUE),
  ('09', 'DAÑO EN NEVERA DEL ALMACEN', 'Devolución de venta', 'CLIENTE', TRUE),
  ('10', 'DEVOLUCION POR TEMPERATURA', 'Devolución de venta', 'LOGISTICA', TRUE),
  ('11', 'NO CUMPLE CON EL TAMAÑO', 'Devolución de venta', 'LOGISTICA / PRODUCCION', TRUE),
  ('12', 'NO PEDIDO POR EL CLIENTE', 'Devolución de venta', 'COMERCIAL / FACTURACION', TRUE),
  ('13', 'ERROR EN DOCUMENTACION DE CALIDAD', 'Devolución de venta', 'CALIDAD', TRUE),
  ('14', 'PERDIDA POR TRANSPORTADORA', 'Devolución de venta', 'LOGISTICA', TRUE),
  ('15', 'AUSENCIA DE MERCADERISTA', 'Devolución de venta', 'VENTAS', TRUE),
  ('16', 'ERROR AL COMPROMETER EL PEDIDO', 'Devolución de venta', 'LOGISTICA', TRUE),
  ('17', 'CAMBIO DE PRECIO', 'Devolución de venta', 'CALIDAD', TRUE),
  ('18', 'VENTAS EN CONSIGNACION', 'Devolución de venta', 'COMERCIAL', TRUE),
  ('A1', 'DIFERENCIA EN PESO(GRAMOS - KILOS)BALANZ', 'Devolución de venta', 'LOGISTICA / PRODUCCION', TRUE),
  ('A2', 'PROBLEMAS DE ROTULADO Y MARCACION', 'Devolución de venta', 'CALIDAD', TRUE),
  ('A3', 'ERROR EN PRECIO', 'Devolución de venta', 'COMERCIAL / FACTURACION', TRUE),
  ('A4', 'FALTANTE M/CIA DIF FACT. VS M/CIA', 'Devolución de venta', 'LOGISTICA', TRUE),
  ('A5', 'ERROR EN TOMA DE PEDIDO - NO CODIFICADO', 'Devolución de venta', 'COMERCIAL /FACTURACION', TRUE),
  ('A6', 'ERROR FECHA FACTURA', 'Devolución de venta', 'FACTURACION / COMERCIAL', TRUE),
  ('B1', 'CLIENTE NO TENIA DINERO', 'Devolución de venta', 'COMERCIAL', TRUE),
  ('B2', 'NO SE ENTREGO A TIEMPO', 'Devolución de venta', 'LOGISTICA', TRUE),
  ('B3', 'ERROR EN DESPACHO', 'Devolución de venta', 'LOGISTICA', TRUE),
  ('B4', 'CANCELADO POR EL CLIENTE', 'Devolución de venta', 'COMERCIAL / CLIENTE', TRUE),
  ('B5', 'ERROR SUCURSAL', 'Devolución de venta', 'COMERCIAL / FACTURACION', TRUE),
  ('B6', 'MALA PRESENTACION', 'Devolución de venta', 'CALIDAD', FALSE),
  ('B8', 'MAL GRAMAJE - SACADO POR LA PLANTA', 'Devolución de venta', 'CALIDAD', FALSE),
  ('B9', 'PROBLEMAS DE ROTULADO', 'Devolución de venta', 'CALIDAD', FALSE),
  ('C1', 'ERROR POR PRECIO- FACTURACION', 'Devolución de venta', 'FACTURACION/VENTAS', FALSE),
  ('C2', 'ERROR EN CANTIDAD(UND/GRAMAJE)-FACTURAC', 'Devolución de venta', 'FACTURACION/VENTAS', FALSE),
  ('C3', 'ERROR DE PRODUCTO- FACTURACION', 'Devolución de venta', 'FACTURACION/VENTAS', FALSE),
  ('C4', 'CANCELADO POR EL CLIENTE', 'Devolución de venta', 'ASESOR COMERCIAL', FALSE),
  ('C5', 'NO PEDIDO POR EL CLIENTE', 'Devolución de venta', 'ASESOR COMERCIAL', FALSE),
  ('C6', 'CLIENTE NO TENIA DINERO', 'Devolución de venta', 'ASESOR COMERCIAL', FALSE),
  ('C7', 'ERROR CLIENTE O SUCURSAL', 'Devolución de venta', 'FACTURACION/VENTAS', FALSE),
  ('C8', 'NO CODIFICADO', 'Devolución de venta', 'FACTURACION/VENTAS', FALSE),
  ('C9', 'DESCUENTO NO APLILCADO', 'Devolución de venta', 'FACTURACION/VENTAS', FALSE),
  ('D1', 'FALTANTE EN PEDIDO', 'Devolución de venta', 'DESPACHOS', FALSE),
  ('D2', 'NO ENTREGA A TIEMPO', 'Devolución de venta', 'DESPACHOS', FALSE),
  ('D3', 'ERROR EN DESPACHO', 'Devolución de venta', 'DESPACHOS', FALSE),
  ('D4', 'FALTANTES POR INVENTARIO', 'Devolución de venta', 'DESPACHOS', FALSE),
  ('E1', 'ORDEN PUBLICO', 'Devolución de venta', 'FUERZA MAYOR', TRUE),
  ('E2', 'CIERRE EN LA VIA', 'Devolución de venta', 'FUERZA MAYOR', TRUE),
  ('E3', 'ERROR EN TARA', 'Devolución de venta', 'LOGISTICA- CAVERO', TRUE)
ON CONFLICT (nombre) DO NOTHING;
