ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS latitud NUMERIC(10,8);
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS longitud NUMERIC(11,8);
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS google_place_id VARCHAR(255);
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS direccion_google VARCHAR(255);
