// Auto-generated by install.sh
// shell/config.js
const PLATFORM_CONFIG = {
  mode: 'test',
  horixUrl: '/horix/',
  horixUrl: '/nomina/',
  proveedoresUrl: '/proveedores/',
  logisticaUrl: '/logistica/',
};
